"""
One-command render + prompt generator for any section.

Usage (from Desktop terminal, while Blender MCP is connected and running):
    python3 run.py <section_name>

Example:
    python3 run.py scalechord
    python3 run.py eq
    python3 run.py header

Produces:
    /Users/ricosan/Downloads/<section>_render.png   (with numbered badges)
    /Users/ricosan/Downloads/<section>_prompt.txt   (ChatGPT prompt, pre-filled)

Then:
    1. Copy prompt.txt + upload PNG to ChatGPT/Gemini/Stitch
    2. Paste the returned TABLE into apply.py and run it in Blender
"""
import json, sys, os
from pathlib import Path

AGENT_DIR = Path(__file__).parent
REG_PATH = AGENT_DIR / "sections.json"
TEMPLATE_PATH = AGENT_DIR / "prompt_template.txt"
OUT_DIR = Path("/Users/ricosan/Downloads")

if len(sys.argv) < 2:
    with open(REG_PATH) as f: reg = json.load(f)
    print("Usage: python3 run.py <section_name>")
    print("Available sections:")
    for k, v in reg["sections"].items():
        print(f"  {k:<16} — {v['description']}")
    sys.exit(0)

section_key = sys.argv[1]
with open(REG_PATH) as f: reg = json.load(f)
if section_key not in reg["sections"]:
    print(f"Unknown section '{section_key}'. Available: {list(reg['sections'].keys())}")
    sys.exit(1)
section = reg["sections"][section_key]

# 1. Write a Blender-executable render script (users run it via mcp or copy-paste)
render_py = OUT_DIR / f"{section_key}_render_in_blender.py"
elements_literal = ",\n    ".join([f"({e[0]!r}, {e[1]!r})" for e in section["elements"]])
render_code = f'''# Auto-generated by blender-redesign agent for section: {section_key}
# Copy-paste into Blender's Scripting tab OR execute via mcp-blender execute_blender_code
import bpy, json
from mathutils import Vector

SECTION_ROOT = {section['root']!r}
ELEMENTS = [
    {elements_literal}
]
OUT_PNG  = "/Users/ricosan/Downloads/{section_key}_render.png"
OUT_JSON = "/tmp/{section_key}_overlay.json"
MARGIN = 0.008
RENDER_W = 1400

def bbox(o):
    mw = o.matrix_world
    bb = [mw @ Vector(c) for c in o.bound_box]
    return min(v.x for v in bb), max(v.x for v in bb), min(v.y for v in bb), max(v.y for v in bb)

root = bpy.data.objects[SECTION_ROOT]
sx1, sx2, sy1, sy2 = bbox(root)

cam = bpy.data.objects.get("Camera")
if cam is None:
    cd = bpy.data.cameras.new("Camera")
    cam = bpy.data.objects.new("Camera", cd)
    bpy.context.collection.objects.link(cam)
bpy.context.scene.camera = cam
cam.data.type = "ORTHO"
cx = (sx1 + sx2)/2; cy = (sy1 + sy2)/2
w  = (sx2 - sx1) + 2*MARGIN
h  = (sy2 - sy1) + 2*MARGIN
cam.data.ortho_scale = max(w, h)
cam.location = (cx, cy, 0.4)
cam.rotation_euler = (0, 0, 0)

scene = bpy.context.scene
scene.render.engine = "BLENDER_WORKBENCH"
scene.display.shading.color_type = "MATERIAL"
H_res = int(RENDER_W * (h/w))
scene.render.resolution_x = RENDER_W
scene.render.resolution_y = H_res
scene.render.image_settings.file_format = "PNG"
scene.render.filepath = OUT_PNG
bpy.ops.render.render(write_still=True)

frame_world_w = cam.data.ortho_scale
frame_world_h = cam.data.ortho_scale * H_res / RENDER_W
x0 = cx - frame_world_w/2
y0 = cy - frame_world_h/2

out = {{"image": OUT_PNG, "width": RENDER_W, "height": H_res, "section": SECTION_ROOT, "elements": []}}
for i, (name, label) in enumerate(ELEMENTS, 1):
    o = bpy.data.objects.get(name)
    if not o: continue
    ex1, ex2, ey1, ey2 = bbox(o)
    out["elements"].append({{
        "num": i, "name": name, "label": label,
        "x1": (ex1-x0)/frame_world_w*RENDER_W,
        "x2": (ex2-x0)/frame_world_w*RENDER_W,
        "y1": H_res - ((ey1-y0)/frame_world_h*H_res),
        "y2": H_res - ((ey2-y0)/frame_world_h*H_res),
    }})

with open(OUT_JSON, "w") as f: json.dump(out, f, indent=2)
print(f"Rendered {{OUT_PNG}} ({{RENDER_W}}x{{H_res}}), {{len(out['elements'])}} elements")
'''
render_py.write_text(render_code)

# 2. Build pre-filled prompt for ChatGPT
with open(TEMPLATE_PATH) as f: template = f.read()
elem_list_str = "\n".join([f"{i+1}. {e[1]} — {e[2]}" for i, e in enumerate(section["elements"])])
w_mm, h_mm = section["expected_size_mm"].split("x")
filled = template.replace("{{ELEMENT_LIST}}", elem_list_str)
filled = filled.replace("{{WIDTH}}", w_mm).replace("{{HEIGHT}}", h_mm)
# Hard-code the n count for strict constraint
n_elements = len(section["elements"])
filled = filled.replace("STRICT CONSTRAINTS (do NOT violate):", f"STRICT CONSTRAINTS (do NOT violate):\n- You MUST use exactly {n_elements} elements (or fewer if you remove). You may NOT add any.")
prompt_path = OUT_DIR / f"{section_key}_prompt.txt"
prompt_path.write_text(filled)

# 3. Summary
print(f"Section: {section_key} — {section['description']}")
print(f"Elements: {len(section['elements'])}")
print()
print("STEP 1: in Blender, run this generated script:")
print(f"  {render_py}")
print("  (or execute it via the mcp-blender execute_blender_code bridge)")
print()
print("STEP 2: run overlay to burn numbered badges:")
print(f"  python3 {AGENT_DIR/'overlay_numbers.py'}")
print(f"  (reads /tmp/{section_key}_overlay.json, writes into the PNG)")
print()
print("STEP 3: open prompt + send to ChatGPT:")
print(f"  open {prompt_path}")
print(f"  open /Users/ricosan/Downloads/{section_key}_render.png")
print()
print("STEP 4: paste the returned table → apply.py")
